### ISSUE TITLE
Entities in a set must have an id property

### ISSUE THREAD

**Issue by jasny** [jasny/entity#3]
In an `EntitySet` each entity can only be there once. For this, the id is checked. If an entity class doesn't have an id, it can't be used for a set. An exception should be thrown when trying to create the set.

**Comment by Minstel** [comment]
This is already implemented in https://github.com/jasny/entity/blob/master/src/EntityCollection/AbstractEntityCollection.php#L101

**Comment by jasny** [comment]
@Minstel This assertion should only be done for an entity set, not a list or map. Please remove it from the general code and put it in the `EntitySet` class only.
